#!/usr/bin/env python

import re

rx = re.compile('#define __NR_(.*?)\s+(\d+)')

print '''\
// Automatically generated by %s

#include "syscall_strings.h"

const char * syscall_string(int syscall_number)
{
   switch(syscall_number)
   {
''' % __file__

for line in open('/usr/include/asm/unistd_64.h', 'r').readlines():
  m = rx.match(line)
  if m:
    print '      case %s: return "%s";' % (m.group(2), m.group(1))

print '''\
      default: return "(unknown)";
   }
}
'''
